import { InstitutionalHeader } from "@/components/sections/institutional-header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Termos de Credenciamento — ParceleCart",
  description: "Leia os termos de credenciamento para utilização dos serviços da ParceleCart.",
  robots: {
    index: true,
    follow: true,
  },
};

export default function CredentialTermsPage() {
  return (
    <main className="min-h-screen">
      <InstitutionalHeader 
        title="Termos de Credenciamento" 
        subtitle="CREDENCIAMENTO PARCELECART"
        lastUpdated="27 de março de 2024"
      />
      
      <div className="px-5 sm:px-8 lg:px-16 xl:px-32 2xl:px-[150px] py-12">
        <div className="w-full text-foreground/90 dark:text-gray-300 space-y-12 leading-relaxed text-base sm:text-lg text-justify mx-auto lg:max-w-5xl">
          
          <section>
            <p className="mb-4">
              O presente documento “Termos de Credenciamento” (doravante denominado “Termos”) apresenta a Serventia Extrajudicial (doravante denominada “Cartório”) esclarecimentos e informações sobre as regras de utilização dos serviços digitais no contexto da plataforma da ParceleCart.
            </p>
            <p>
              Estes Termos aplicam-se aos serviços oferecidos pela PCART SOLUÇÕES EM PAGAMENTO S.A., sociedade empresária limitada, inscrita no CNPJ/MF sob o nº 46.037.774/0001-98, com sede na Cidade de São Paulo, Estado de São Paulo, na Av. São Gabriel, nº 201, Conj. nº 105, Jardim Paulista - CEP 01435-001, sob o endereço eletrônico www.parcelecart.com.br, a qual realiza a intermediação, de jeito simples e seguro, de pagamentos e parcelamentos de custas e emolumentos cartorários e impostos.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">I. DO ACEITE DOS TERMOS</h2>
            <p>
              O Cartório deverá ler com atenção as condições estabelecidas neste documento para se certificar das regras descritas, uma vez que este documento vincula direitos e obrigações entre o Cartório e a ParceleCart. Em caso de discordância de alguma cláusula, recomendamos a abstenção da navegação, bem como o encerramento da utilização dos nossos serviços. Estes Termos poderão ser alterados a qualquer tempo caso haja necessidade. Por isso, recomenda-se que esta seção seja consultada com regularidade e verificada a data de modificação. Ao assinar a Ficha de Credenciamento, o Cartório declara estar de acordo com as cláusulas deste documento.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">II. DO OBJETO</h2>
            <div className="space-y-4">
              <p>2.1. O presente Termo tem por objeto a disponibilização, pela ParceleCart ao Cartório, diretamente ou através de terceiros integrantes da sua rede de parceiros, de serviços de gestão de pagamentos, por conta e ordem do Cartório, consistente na disponibilização de solução para: (i) a captura e processamento de Transações realizadas por meio de Cartões; (ii) pagamentos via Pix e Boleto Bancário; e (iii) a transferência de valor líquido das Transações, desde que cumpridos os termos e condições deste Termo (doravante “Serviços”).</p>
              <p>2.1.1. Em contrapartida à prestação dos Serviços acima, a ParceleCart será remunerada na forma definida nos Termos Gerais de Contratação.</p>
              <p>2.1.2. Os Serviços são prestados mediante a licença de uso das tecnologias de propriedade da ParceleCart e/ou de seus parceiros.</p>
              <p>2.2. O Cartório, neste ato, outorga poderes à ParceleCart para que atue, na forma do art. 653 e seguintes, do Código Civil Brasileiro, para os fins de executar transações em meios de pagamento eletrônico, bem como a prática de qualquer outro ato necessário para a prestação dos Serviços, inclusive, a celebração de contratos com credenciadoras e outros prestadores de serviço necessários para a realização de operações de pagamento em arranjos abertos.</p>
              <p>2.3. Fazem ainda parte integrante do presente Termo eventuais termos de uso dos Serviços que de tempos em tempos venham a ser publicados no website da ParceleCart.</p>
              <p>2.4. As Partes expressamente declaram-se cientes de que os Serviços se destinam tão somente a viabilizar a realização de Transações em moeda corrente nacional realizadas por meio de pagamento eletrônico no território nacional.</p>
              <p>2.5. O Cartório reconhece e declara que a ParceleCart é mera intermediadora e facilitadora de pagamentos no âmbito da relação jurídica estabelecida entre o Cartório e o portador do cartão, ficando a ParceleCart isenta de qualquer responsabilidade relativa ao conteúdo das Transações, condições comerciais oferecidas pelo Cartório.</p>
              <p>2.6. É parte integrante do presente contrato a Proposta Comercial enviada previamente pela ParceleCart ao Cartório.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">III. DO CADASTRAMENTO</h2>
            <div className="space-y-4">
              <p>3.1. Para utilizar o Serviços, o Cartório deverá informar, em local indicado pela ParceleCart, todos os dados exigidos, responsabilizando-se civil e criminalmente pela veracidade das informações.</p>
              <p>3.2. A ParceleCart poderá realizar processo de verificação do Cartório de acordo com as regras sobre prevenção e combate aos crimes de lavagem de dinheiro, de terrorismo e seu financiamento, entre outros, e ocultação de bens especificados pela Lei nº 9.613 de 03 de março de 1998, e pelo Conselho de Controle de Atividades Financeiras – COAF, além de outras legislações e regulamentações aplicáveis às hipóteses.</p>
              <p>3.3. O início da prestação dos Serviços pela ParceleCart está condicionado à aprovação do cadastro do Cartório pela ParceleCart, conforme seus critérios de avaliação.</p>
              <p>3.4. O Cartório autoriza a ParceleCart, a vistoriar durante o horário de funcionamento do Cartório, (i) a regularidade e permanência de suas atividades declaradas para utilização dos Serviços, nos termos deste Termo; (ii) a regularidade na realização das Transações, (iii) o funcionamento dos equipamentos; e (iv) a adequada guarda, o consumo e o abastecimento de todo e qualquer material necessário à realização das Transações.</p>
              <p>3.5. O Cartório, neste ato, autoriza expressamente que seus dados sejam mantidos pela ParceleCart, bem como autoriza seu fornecimento (i) às autoridades públicas competentes que os solicitarem formalmente, nos termos da legislação brasileira; (ii) aos seus Cartórios estratégicos, técnicos, com a finalidade de disponibilizar melhores serviços ao Cartório. O Cartório declara expressamente e concorda que a ParceleCart colete informações para realização de acompanhamento de tráfego.</p>
              <p>3.6. O Cartório deverá manter seus dados cadastrais sempre atualizados, informando as alterações necessárias por meio de envio de e-mail a ParceleCart.</p>
              <p>3.7. A ParceleCart deverá, ainda, criar uma conta em seu website para que a Cartório possa utilizar os Serviços.</p>
              <p>3.7.1. O Cartório deverá obrigatoriamente fornecer um endereço eletrônico (e-mail) para comunicação com a ParceleCart e mantê-lo atualizado. As Partes reconhecem o e-mail cadastrado no ato do cadastramento como forma válida e eficaz de comunicação e aceitam como suficiente para os serviços que se refiram a este contrato.</p>
              <p>3.7.2. Caso o Cartório suspeite ou tome ciência de que usa conta foi utilizada sem a sua autorização, deverá notificar imediatamente a ParceleCart e alterar sua senha de acesso, sendo que a ParceleCart não se responsabiliza por quaisquer problemas relacionados à inobservância do disposto nesta cláusula.</p>
              <p>3.8. O Cartório deverá, obrigatoriamente, possuir uma conta bancária de sua titularidade, mantida no Brasil junto a uma instituição financeira devida e regularmente constituída ou autorizada a funcionar no território nacional, para a finalidade deste Termo.</p>
              <p>3.9. As Partes comprometem-se a seguir todas as regras e exigências determinadas pelas Credenciadoras e Bandeiras, pelo mercado de Meios de Pagamento e pela legislação, tenham sido elas estipuladas no passado ou venham a ser no futuro, após sua informação pela ParceleCart e decorrido o prazo para o respectivo cumprimento, sendo certo que seu descumprimento pode acarretar a rescisão deste Termo.</p>
              <p>3.10. O Cartório poderá requerer a vinculação de um ou mais equipamentos sob sua responsabilidade ao seu cadastro na ParceleCart, sendo que, neste caso, a ParceleCart avaliará o pedido confirme critérios próprios e sujeitos a cobrança para sua realização, podendo aprová-lo ou recusá-lo.</p>
              <p>3.11. Quando do credenciamento do Cartório ou durante a vigência do Contrato, serão definidos, conforme solicitação do Cartório e critérios adotados pela ParceleCart, os Cartões que o Cartório poderá aceitar e os tipos de Transações e formas de captura de Transações que o Cartório estará autorizado a realizar.</p>
              <p>3.12. O Cartório deverá comunicar à ParceleCart, em até 15 (quinze) dias corridos de sua ocorrência, quaisquer alterações relativas às informações prestadas à ParceleCart, inclusive, endereços comerciais e eletrônicos, endereços de correspondência ou números de telefone, respondendo, nos termos da lei, pela veracidade das informações prestadas à ParceleCart e por eventual divergência entre os dados informados e os dados reais e/ou oficiais.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">IV. DAS TRANSAÇÕES</h2>
            <div className="space-y-4">
              <p>4.1. As Transações serão realizadas por meio dos equipamentos, sendo que cada transação será evidenciada por um registro em um formulário aprovado como um recibo de vendas físico ou virtual, o qual conterá informações dos valores da venda para o titular de cartão de crédito ou débito do cartão (“Recibo de Vendas”).</p>
              <p>4.1.1. As Transações somente serão concluídas quando forem aprovadas pela ParceleCart, pela credenciadora e pela bandeira, e desde que atendidas o disposto neste Termo. As Transações nos equipamentos somente podem ser realizadas com Cartões das Bandeiras credenciadas. Qualquer alteração quanto à aceitação de Bandeiras de Cartões será comunicada no website da ParceleCart.</p>
              <p>4.2. Fica desde já esclarecido que o equipamento somente realiza Transações em Cartões com chip ou aproximação, não sendo possível a realização de Transações manuais e/ou com a leitura de tarja dos Cartões.</p>
              <p>4.3. O Cartório deve utilizar o equipamento e os Serviços somente para realizar Transações regulares, em moeda corrente nacional, estritamente de acordo com normas e condições deste Termo, sendo vedado aceitar os Cartões em Transações fictícias ou simuladas, tais como, mas não limitadas a: (a) fornecer ou restituir aos titular de cartão de crédito ou débito, conforme regras de uso do cartão, quantias em dinheiro (moeda nacional ou estrangeira, cheques, ordens de pagamento ou títulos de crédito); (b) qualquer outro tipo ou forma de Transações consideradas irregulares e decorrentes de atividades consideradas ilegais ou indesejáveis, conforme estabelecido pela ParceleCart, pelas Credenciadoras, Emissores e pelas Bandeiras; (c) utilizar os equipamentos, sem autorização prévia da ParceleCart, em outro local que não o seu endereço cadastrado com a ParceleCart; (d) realizar Transações com a finalidade de garantia ou caução, sem a devida autorização da ParceleCart; (e) efetuar Transações não relacionadas com o ramo de atividade cadastrado na ParceleCart.</p>
              <p>4.3.1. O Cartório se compromete a não efetuar Transações em segmentos ou ramos de atividades diversos daqueles informados pelo Cartório no momento de seu cadastro e registrado na sua conta na ParceleCart.</p>
              <p>4.3.2. Qualquer alteração no segmento de atuação ou no ramo de atividade do Cartório deve ser informada à ParceleCart, imediatamente, que em caso de aprovação, efetuará a alteração cadastral, ficando o Cartório ciente que tal alteração pode levar a uma nova negociação comercial de taxas e tarifas dos Serviços.</p>
              <p>4.3.3. Cartório se compromete a não utilizar o serviços para Transações, que incluam, ainda que parcialmente: (i) atividades ilegais, tais como bestialidade, pedofilia, tráfico de droga e lavagem de dinheiro; (ii) armas de fogo e jogos de azar, inclusive bingo; (iii) equipamentos hospitalares, medicamentos em geral e qualquer tipo de drogas ou produtos aos quais se atribua efeitos terapêuticos; (iv) venda de animais, (v) produtos pendentes de homologação de órgãos governamentais, (vi) ações, valores mobiliários ou qualquer tipo de produtos financeiros; e (vii) agências de empregos, escritórios de cobrança, consórcios e comercialização de cartão de desconto.</p>
              <p>4.3.4. Eventual transação realizada pelo Cartório que viole estes termos ou a legislação aplicável (incluindo, entre outros, transação que caracterize fraude ou ato criminal), não será autorizada ou ficará sujeita a estorno.</p>
              <p>4.3.5. A prestação dos Serviços será imediatamente encerrada pela ParceleCart caso se verifique que Transações realizadas pelo Cartório foram deliberadamente fraudadas por ele, seus colaboradores, contratados ou prepostos.</p>
              <p>4.4. O Cartório está ciente de que será descredenciado caso atinja um percentual de Transações suspeitas ou irregulares conforme definição das Credenciadoras e/ou Bandeiras e regras de monitoramento de fraude da ParceleCart, bem como se atingir índices de contestação de Transações além dos limites estabelecidos pela ParceleCart, Credenciadoras e/ou pelas Bandeiras.</p>
              <p>4.5. O Cartório, na consecução de suas atividades e realização de Transações, não poderá utilizar recursos tecnológicos, hardware, software or qualquer outra tecnologia não homologada ou não autorizada pela ParceleCart e/ou que venha a trazer riscos de fraude ou segurança para os Serviços e/ou equipamento que estejam em desacordo com as normas e padrões internacionais da indústria de Cartões. As Transações deverão ser capturadas, processadas, roteadas, liquidadas e compensadas apenas por intermédio da solução tecnológica da ParceleCart, e devem estar em consonância com normas, procedimentos e autorizações das Credenciadoras e/ou bandeira e do mercado de Meios de Pagamento.</p>
              <p>4.6. O Cartório se compromete colaborar com a ParceleCart, com os instituidores de Meios de Pagamento e órgãos de fiscalização no fornecimento de dados e informações relativas às Transações, incluindo, mas sem se limitar, ao que se refere à prevenção e combate aos crimes de lavagem de dinheiro, ocultação de bens, financiamento ao terrorismo e crimes contra crianças e adolescentes.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">V. CONTESTAÇÃO DE TRANSAÇÕES – CHARGEBACK – E CANCELAMENTO DAS TRANSAÇÕES</h2>
            <div className="space-y-4">
              <p>5.1. Na hipótese de contestação de Transações, a ParceleCart receberá a informação das Credenciadoras e solicitará ao Cartório, quando cabível, a comprovação da transação.</p>
              <p>5.1.1. Na hipótese da Contestação de Transação, o Cartório reconhece e concorda que prestará a ParceleCart, às Credenciadoras, às Bandeiras ou aos bancos Emissores, informações disponíveis para efetivar um estorno.</p>
              <p>5.2. A transação, mesmo após ser autorizada, poderá não ser processada ou ser cancelada pela ParceleCart, a seu exclusivo critério e a qualquer tempo, nas seguintes hipóteses: (i) se for constatada a ocorrência de irregularidades e/ou de circunstâncias que caracterizem indícios ou suspeita de fraudes, nos termos deste Termo; (ii) se não houver reconhecimento da transação pelo titular de cartão de crédito ou débito, em razão de suspeita de fraude; ou (iii) ocorrendo o não cumprimento, pelo Cartório, dos termos deste Termo e suas respectivas atualizações, bem como a legislação aplicável.</p>
              <p>5.2.1. Para a autorização da transação de forma geral (a) são verificados pelo emissor do cartão se ele não se encontra bloqueado e se a transação possui valor dentro dos limites do titular de cartão de crédito ou débito, assim, (b) a autorização da transação com a liberação do código de autorização pela ParceleCart não caracteriza qualquer tipo de declaração da ParceleCart quanto à regularidade da transação, sendo possível, posteriormente, que sejam detectadas irregularidades na transação justificando seu cancelamento.</p>
              <p>5.3. Caso a transação seja estornada, por chargeback, pela credenciadora e/ou pelo emissor do cartão de acordo com as regras e regulamentações operacionais das Bandeiras e/ou das Credenciadoras, o valor dessa transação será garantido pela ParceleCart, que fará a restituição do valor ao Cartório.</p>
              <p>5.3.1. A regra acima não será aplicada nas seguintes situações: (i) se a transação não for comprovada pela exibição do recibo de venda, da nota fiscal, contrato e/ou do respectivo comprovante de entrega de mercadoria ou serviço e/ou dos outros documentos que venham a ser exigidos pela ParceleCart; (ii) se o Recibo de Vendas estiver adulterado ou danificado; (iii) Se o Recibo de Vendas for falsificado ou copiado de outro; (iv) se houver ordem de autoridade legítima impedindo o repasse e/ou determinando o bloqueio, penhora, arresto, custódia ou depósito dos créditos do Cartório; (v) se o Cartório realizar transação ilícita.</p>
              <p>5.4. O Cartório pode solicitar, mediante condições estabelecidas a critério da ParceleCart e/ou das Credenciadoras, o cancelamento das Transações na modalidade crédito no prazo de 30 (trinta) dias e o cancelamento das Transações na modalidade débito no prazo de 5 (cincos) dias, a contar da data da realização da respectiva transação, sendo que a ParceleCart terá o prazo de até 10 (dez) dias para análise do procedimento de cancelamento para responder ao Cartório sobre a possibilidade de cancelamento ou não daquela transação específica.</p>
              <p>5.4.1. Se o Cartório solicitar o cancelamento das Transações antes do recebimento do valor da transação, a transação será cancelada e não será efetuado o respectivo pagamento.</p>
              <p>5.4.2. Se o Cartório solicitar o cancelamento das Transações e o pagamento da transação já tiver sido efetuado ao Cartório, total ou parcialmente, mesmo que por antecipação, a ParceleCart cancelará a transação, e descontará da próxima agenda de recebíveis do Cartório.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">VI. DOS EQUIPAMENTOS</h2>
            <div className="space-y-4">
              <p>6.1. Para utilização dos Serviços, o Cartório deverá utilizar um ou mais equipamentos homologados pela ParceleCart, nos termos e condições estabelecidos neste Termo.</p>
              <p>6.2. Os equipamentos citados no presente Termo serão utilizados, exclusivamente, para execução dos serviços da ParceleCart, os quais serão disponibilizados por tempo indeterminado em regime de comodato.</p>
              <p>6.3. A qualquer momento, mediante aviso prévio, a ParceleCart poderá solicitar a devolução do equipamento e encerrar o comodato, mediante justificativa.</p>
              <p>6.4. A instalação e desinstalação dos equipamentos poderão ser realizadas pela ParceleCart ou por terceiros por ela indicados, no endereço informado pelo Cartório.</p>
              <p>6.5. Mediante solicitação e análise prévia, a ParceleCart poderá, a seu critério, fornecer ao Cartório mais de um equipamento vinculado a conta do mesmo Cartório, conforme condições comerciais a serem definidas por ocasião do fornecimento.</p>
              <p>6.6. Aceito o pedido de comodato, o equipamento será entregue no endereço indicado pelo Cartório em seu cadastro.</p>
              <p>6.7. O Cartório instalará todas e quaisquer atualizações disponibilizadas pela ParceleCart, de modo a assegurar a continuidade do uso dos Serviços. A ParceleCart não se responsabilizará por quaisquer falhas na prestação dos Serviços relacionados à inobservância do disposto nesta cláusula.</p>
              <p>6.8. O Cartório reconhece e concorda que os equipamentos utilizam conectividade sem fio para possibilitar a realização de Transações.</p>
              <p>6.9. Em relação aos equipamentos, o Cartório obriga-se a: ( a ) usar os equipamentos corretamente, respeitando estritamente os termos de uso da ParceleCart; ( b ) manter os equipamentos no local de instalação informado no cadastro ou em outro local autorizado pela ParceleCart, devendo comunicar previamente a ParceleCart em caso de qualquer mudança, não podendo ceder, sublocar, transferir ou alienar, total ou parcialmente, os equipamentos sem a anuência da ParceleCart; ( c ) adotar todas as providências e cautelas necessárias para manter a guarda, a integridade e a perfeita conservação e funcionamento dos equipamentos, sendo vedado ao Cartório realizar qualquer reparação ou modificação em tais equipamentos, comprometendo-se a comunicar imediatamente à ParceleCart qualquer intervenção ou violação por terceiros de quaisquer dos seus direitos relativamente ao equipamento; (e) reconhecer e concordar que os softwares aplicativos cedidos ou inseridos nos equipamentos são de titularidade da ParceleCart ou de terceiros e incorporam a propriedade intelectual da ParceleCart ou de tais terceiros, podendo o Cartório apenas fazer uso deles, comprometendo-se a não ceder, copiar, alterar, modificar, adaptar, manipular, adicionar, decompilar, decompor ou efetuar qualquer conversão dos softwares, sendo vedado também o uso de engenharia reversa ou utilização para fins diversos dos previstos no presente Termo, sob pena de imediata rescisão do Termo, sem prejuízo do ressarcimento por eventuais perdas e danos acarretados; (f) assumir a total responsabilidade, nos seguintes casos: furto, roubo, perda total ou parcial, incêndio, destruição total ou parcial, descuido no manuseio; (g) em casos de furto ou roubo, incêndio ou destruição total ou parcial, o Cartório deverá apresentar comunicar imediatamente a ParceleCart e fazer o respectivo Boletim de Ocorrência, que deve constar, obrigatoriamente, os dados que identifiquem o equipamento; (h) comunicar imediatamente à ParceleCart caso haja suspeita de fraude ou fraude confirmada no equipamento.</p>
              <p>6.10. O Cartório reconhece o direito da ParceleCart de efetuar interrupções no fornecimento dos Serviços e desde já declara que tem conhecimento pleno de que os Serviços poderão, eventualmente, ser afetados, ou temporariamente interrompidos por motivos técnicos, em razão de reparo, manutenção ou troca de equipamento.</p>
              <p>6.11. Tendo em vista a impossibilidade de funcionamento integral e ininterrupto de qualquer sistema de telecomunicação ou de informática, durante 365 (trezentos e sessenta e cinco) dias por ano, 24 (vinte e quatro) horas por dia, nesta situação de fragilidade também se incluindo, em razão de sua complexidade, a disponibilização do serviços, inclusive em razão da dependência de serviços de telecomunicações prestados por terceiros, a ParceleCart não garante, de nenhuma forma, a prestação dos serviços de forma ininterrupta ou isenta de erros e não se responsabiliza pela impossibilidade de se realizarem Transações durante os períodos de indisponibilidade do serviços.</p>
              <p>6.12. A ParceleCart não se responsabiliza por eventuais falhas, atrasos ou interrupções nos Serviços decorrente de caso fortuito ou motivos de força maior, bem como por limitações impostas por parte do Poder Público ou decorrentes da atuação de operadoras de serviço de telecomunicações interconectadas à rede do Cartório, ou, ainda, por má utilização do serviço pelo Cartório ou por qualquer outro fato alheio à vontade da ParceleCart.</p>
              <p>6.13. Os equipamentos disponibilizados permanecerão na posse do Cartório pelo prazo do Termo, na pessoa de seu representante legal, que expressamente aceita o encargo de fiel depositário dos equipamentos. As partes concordam expressamente que não será devida, pela Cartório, qualquer remuneração pelo depósito do equipamento estabelecido nesta cláusula.</p>
              <p>6.14. Em caso de rescisão ou término deste Termo ou no caso de devolução de um equipamento específico o aparelho, acrescido de seus respectivos periféricos, deverá ser devolvido pelo Cartório à ParceleCart no mesmo estado em que recebeu, no prazo máximo de 7 (sete) dias contados da rescisão, cancelamento ou término, podendo tal prazo ser prorrogado a critério da ParceleCart. Caso o Cartório não devolva o equipamento da ParceleCart no prazo acima mencionado, a ParceleCart poderá cobrar do Cartório o valor de nota fiscal do equipamento. A ParceleCart fica desde já autorizada a realizar o referido débito. Caso não seja possível o débito do valor de nota fiscal do equipamento não devolvido pelo Cartório, a ParceleCart poderá utilizar todos os meios possíveis de cobrança do seu crédito, inclusive incluindo o nome do Cartório nos órgãos de proteção ao crédito.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">VII. REMUNERAÇÃO DA PARCELECART E ANTECIPAÇÃO DE RECEBÍVEIS</h2>
            <div className="space-y-4">
              <p>7.1. Em decorrência dos serviços oferecidos pela ParceleCart, o Cartório está ciente que os usuários que optarem pelo pagamento das custas e emolumentos através das soluções da ParceleCart, concordam em pagar os percentuais descritos na Proposta Comercial enviada previamente pela ParceleCart.</p>
              <p>7.2. Fica estabelecido que toda e qualquer transação oriunda do presente contrato terá seu valor líquido antecipado ao Cartório em um dia útil, conforme as cláusulas do presente Termo.</p>
              <p>7.3. Os valores devidos à ParceleCart e à Credenciadora serão debitados automaticamente do valor bruto da transação, sendo repassado ao Cartório apenas o valor líquido.</p>
              <p>7.4. A ParceleCart poderá efetuar reajuste dos valores indicados na Proposta Comercial informando previamente ao Cartório, por e-mail, com um prazo mínimo de 7 (sete) dias de antecedência ao reajuste. Caso o Cartório não concorde com as novas condições de remuneração, poderá encerrar o presente Termo. O não encerramento do Termo pelo Cartório será interpretado como anuência aos novos valores e tarifas.</p>
              <p>7.5. O Cartório está ciente e concorda desde já que nas hipóteses em que as tarifas e/ou taxas cobradas pelas Bandeiras e Credenciadoras sofrerem quaisquer reajustes, referidos reajustes deverão ser refletidos na remuneração da ParceleCart prevista no presente Termo, de forma a assegurar o equilíbrio econômico-financeiro da prestação do Serviços, objeto do presente Termo.</p>
              <p>7.6. Não serão realizados repasses de Transações para contas bancárias de titularidade de terceiros, que não estejam em nome do Cartório ou que seja mantida em instituição fora do território nacional e/ou não regularmente constituída ou autorizada a funcionar no território brasileiro.</p>
              <p>7.7. O Cartório, nos termos do Art. 286 a 298 do Código Civil e demais legislações aplicáveis, desde já, cede à ParceleCart, os recebíveis (créditos) oriundos das Transações realizadas no contexto do presente Contrato. O presente instrumento servirá como competente outorga de poderes, na forma do art. 654 e seguintes do Código Civil. O Cartório não se opõe à livre negociação desses recebíveis no mercado, sendo resguardado ao Cartório, contudo, o Repasse do valor de cada Transação, nos termos do presente Contrato.</p>
              <p>7.8. Caso o Cartório deseje antecipar seus recebíveis, deverá solicitar junto à ParceleCart, conforme disponibilidade e respectivas condições aplicáveis. Fica estabelecido que toda e qualquer contratação de acordo operacional, bem como toda e qualquer negociação, antecipação ou cessão (independente da forma comercial ou jurídica a ser adotada) em relação a recebíveis de quaisquer meios de pagamentos já existentes ou futuros que implicarem em ações a serem tomadas pela ParceleCart e/ou gerarem ônus, riscos, impactos sistêmicos ou operacionais para ParceleCart, ficam sujeitos à sua anuência. A ParceleCart verificará e informará ao Cartório, através da central de atendimento, se o Cartório está apto a negociar a antecipação de seus recebíveis.</p>
              <p>7.9. Caso a ParceleCart, após anuir com a negociação de recebíveis, por qualquer motivo, suspeite de alguma Transação, poderá reter o fluxo até o máximo de 30 (trinta)dias úteis. Período este, que deverá ser utilizado para confirmação de dados e validação das informações, sendo que o Cartório se compromete a fornecer toda e qualquer informação necessária para a condução desse processo.</p>
              <p>7.10. É vedado ao Cartório negociar os recebíveis das Transações objeto do presente Termo com terceiros, salvo mediante prévia e expressa autorização da ParceleCart.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">VIII. DO PIX E DO BOLETO BANCÁRIO: DO PRESTADOR DA SOLUÇÃO TECNOLÓGICA DE BANCO COMO SERVIÇO (“BANKING AS A SERVICE”/”BAAS”)</h2>
            <div className="space-y-4">
              <p>8.1. O Cartório está ciente e concorda que (i) as suas transações via Pix e Boleto Bancário serão executadas pela ParceleCart, e que (ii) a conta de pagamento de sua titularidade poderá ser aberta e custodia pela CELCOIN INSTITUIÇÃO DE PAGAMENTO S.A, inscrita no CNPJ nº 13.935.893/0001-09 (“CELCOIN”), empresa parceira contratada pela ParceleCart, para prestação da solução tecnológica de Banco como Serviço (“Bank as a Service”/”BaaS”),que contempla os procedimentos de abertura e gerenciamento de contas de pagamento, emissão de moeda eletrônica e serviços de processamento e liquidação.</p>
              <p>8.2. O Cartório está ciente e concorda que todos os dados fornecidos para abertura e manutenção da conta, serão utilizados pela CELCOIN apenas para o cumprimento da relação contratual firmada com a ParceleCart, dos deveres advindos da regulamentação vigente, sempre em observância a legislação que versa sobre proteção de dados e segurança da informação. A CELCOIN poderá, a qualquer momento, solicitar informações complementares para fins legais e regulatórios.</p>
              <p>8.3. Do mandato: o Cartório, pelo presente instrumento, outorga, de forma irrevogável e irretratável, a ParceleCart como sua mandatária perante a CELCOIN, autorizando e concedendo-lhe poderes específicos para, por sua conta e ordem, realizar movimentações de recursos financeiros de sua titularidade depositados na CELCOIN, para liquidação e realização de transações financeiras objeto do presente contrato. As transações somente serão liquidadas em contas de titularidade do Cartório.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">IX. REPASSE DE VALORES</h2>
            <div className="space-y-4">
              <p>9.1. Os valores das Transações serão disponibilizados ao Cartório em até um dia útil, desde que a transação tenha sido realizada de acordo com este Termo, e depois de deduzidas a remuneração, taxas e encargos aplicáveis.</p>
              <p>9.2. A Credenciadora ou a ParceleCart creditarão na conta do Cartório o valor líquido das Transações realizadas, conforme termos e condições previstas neste Termo. Ao ser efetuado o crédito ao Cartório antes do vencimento da fatura do titular de cartão de crédito ou débito, estes se sub-rogam automaticamente nos direitos de crédito contra o titular de cartão de crédito ou débito.</p>
              <p>9.2.1. Caso a data prevista para o repasse do valor líquido da transação recair em feriado ou em dia de não funcionamento bancário, o repasse será realizado no primeiro dia útil subsequente.</p>
              <p>9.2.2. Nas hipóteses de falha técnica e/ou operacional nos sistemas, a Credenciadora ou a ParceleCart poderão, sem incorrer em qualquer ônus ou penalidade, exceder em até um dia útil o prazo estabelecido para efetuar o pagamento relativo a qualquer tipo de transação.</p>
              <p>9.2.3. O pagamento dos valores das Transações ao Cartório estará sujeito a condições normais de operacionalidade do sistema de pagamentos em questão, sendo que eventuais interrupções ou falhas do sistema poderão impactar a agenda de pagamento ao Cartório.</p>
              <p>9.2.3.1. Caso a Credenciadora não liquide os valores ao Cartório até às 15 horas do dia útil seguinte à data da transação, a ParceleCart se responsabiliza por liquidar os respectivos valores ao Cartório, que restituirá estes à ParceleCart quando do recebimento pela Credenciadora.</p>
              <p>9.2.4. Nos casos em que se verificar a iliquidez, insolvência, pedido de recuperação judicial ou extrajudicial, estado pré-falimentar, encerramento de atividades ou qualquer outra hipótese em que ficar caracterizada, a exclusivo juízo da ParceleCart, segundo critérios razoáveis, a dificuldade do Cartório em cumprir suas obrigações contratuais e/ou legais, a ParceleCart reserva-se o direito de, mediante aviso por escrito ao Cartório, reter os créditos a ele devidos, a fim de garantir o cumprimento de suas obrigações perante a Cartório.</p>
              <p>9.3. O Cartório terá o prazo de 30 (trinta) dias corridos a partir da data do crédito na conta do Cartório para apontar qualquer diferença nos valores a crédito ou a débito que compõem o repasse da transação efetuada. Terá, ainda, o mesmo prazo, contando-se da data em que o repasse deveria ter sido efetuado, para solicitar explicações de repasses não realizados. Findo esse prazo, a quitação do valor do repasse da transação será irrestrita e irrevogável.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">X. PRAZO DO TERMO E HIPÓTESES DE RESCISÃO E SUSPENSÃO DOS SERVIÇOS</h2>
            <div className="space-y-4">
              <p>10.1. O presente Termo vigorará por prazo indeterminado a contar da data de assinatura.</p>
              <p>10.1.1. Caso a serventia extrajudicial encontre-se em período de interinidade e tenha sua situação alterada para provida, por investidura de um oficial concursado na delegação, o presente termo poderá ser rescindido sem comunicação do aviso prévio de 30 (trinta) dias de antecedência de que trata a cláusula 10.1.2 abaixo.</p>
              <p>10.1.2. O presente Termo poderá ser resilido, integral ou parcialmente, sem ônus ou multa, por qualquer Parte, a qualquer tempo, mediante aviso prévio por escrito à outra parte com pelo menos 30 (trinta) dias de antecedência, responsabilizando-se as partes, nos termos e condições do presente, pelas Transações já realizadas e pelas obrigações com caráter perene ou cujos prazos se estendam além do término da vigência deste Termo.</p>
              <p>10.1.3. Em caso de resilição caberá à ParceleCart efetuar os repasses porventura devidos ao Cartório, nos prazos estabelecidos neste Termo, ficando plenamente quitada das suas obrigações decorrentes deste Termo, sem prejuízo das perdas e danos aplicáveis, e caberá ao Cartório pagar ou restituir de imediato à ParceleCart as quantias eventualmente a ela devidas, na forma deste Termo, sem prejuízo das perdas e danos aplicáveis.</p>
              <p>10.2. Este Termo será rescindido de pleno direito, independentemente de notificação, interpelação judicial ou extrajudicial, na hipótese de falência, recuperação judicial ou extrajudicial ou insolvência de qualquer das partes, decretada ou requerida.</p>
              <p>10.3. Também motiva a rescisão de pleno direito, sem prejuízo do ressarcimento das perdas e danos eventualmente acarretados, o não cumprimento pelas Partes, de qualquer das cláusulas ou obrigações dispostas neste Termo ou em qualquer dos documentos que compõem, ou ainda nas seguintes hipóteses: (i) se o Cartório, sem autorização da ParceleCart, ceder a terceiros, mesmo parcialmente, quaisquer direitos e/ou obrigações decorrentes deste Termo e/ou a cessão de uso dos equipamentos; (ii) se o Cartório ficar impedido de abrir ou mantiver conta corrente de depósitos em instituições financeiras ou caso fique, por qualquer período de tempo e por qualquer motivo, sem Domicílio Bancário para receber seus créditos transferidos diretamente da ParceleCart ; (iii) se o Cartório realizar Transações consideradas ilegítimas, fraudulentas ou que infrinjam o disposto neste Termo ou que pretendam burlar ou descumprir o Termo, quaisquer regras ou requisitos operacionais ou de segurança da ParceleCart, Credenciadoras ou das Bandeiras, ou qualquer lei ou regulamento municipal, estadual ou federal; (iv) se qualquer das informações, declarações escritas ou verbais prestadas pelo Cartório, incluindo, mas não se limitando àquelas constantes em seu cadastro bem como representação legal e dados cadastrais do Cartório não corresponderem com a verdade ou não forem atualizadas pelo Cartório em, no máximo 30 (trinta) dias, em caso de alteração; (v) por determinação da credenciadora e/ou da bandeira neste sentido; (vi) caso o Cartório, de qualquer forma, comprometer a imagem pública da ParceleCart e/ou de seus Cartórios comerciais;</p>
              <p>10.3.1. Nos casos previstos nesta cláusula acima, a ParceleCart não estará obrigada a cumprir o prazo de 30 (trinta) dias podendo efetivar a rescisão no momento de sua ciência da ocorrência de quaisquer das hipóteses acima.</p>
              <p>10.4. Caso o término do presente contrato por culpa do Cartório, a ParceleCart poderá bloquear o acesso do Cartório a todos os Serviços.</p>
              <p>10.5. A rescisão do presente Termo, por qualquer motivo, não prejudicará o direito da ParceleCart de haver as quantias porventura devidas pelo Cartório relativamente ao Serviços prestado anteriormente à rescisão, nem o de haver a indenização porventura devida pelo Cartório.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">XI. DIREITOS AUTORAIS E DE PROPRIEDADE INTELECTUAL</h2>
            <div className="space-y-4">
              <p>11.1. Toda e qualquer atribuição dos Serviços, bem como as marcas, logotipos, solução tecnológica, aplicativo e demais conteúdos utilizados no âmbito deste Termo é de propriedade da ParceleCart ou de seus prestadores de serviços e estão protegidas pelas normas de direitos autorais, direitos de marca e de propriedade intelectual e demais normas aplicáveis, sendo vedada a sua reprodução, cópia ou qualquer outra forma de utilização comercial ou divulgação não autorizada.</p>
              <p>11.2. Se o Cartório utilizar algum programa da ParceleCart – como uma API (Interface de Programação de Aplicativos), um kit de desenvolvimento ou outro programa que o Cartório tenha feito o download para o seu computador, dispositivo ou outra plataforma, a ParceleCart lhe concede uma licença gratuita revogável, não exclusiva e intransferível para uso desse programa de acordo com os termos e regras da ParceleCart informadas a você quando de sua adesão aos Serviços da ParceleCart. A concessão dessa licença inclui o programa e todas suas atualizações, upgrades, novas versões e programas substitutos. O Cartório não poderá ceder, sublicenciar ou de outra forma transferir seus direitos relativos ao programa para terceiros. O Cartório deverá obedecer aos requisitos de implementação e restrições de uso contido na documentação da ParceleCart que acompanha os Serviços da ParceleCart e que foi disponibilizada ao Cartório. Se não o fizer, o Cartório será responsável por todos os danos e prejuízos resultantes da infração sofridos pelo Cartório, pela ParceleCart ou por terceiros. O Cartório se compromete a não alterar, reproduzir, adaptar, distribuir, exibir, publicar, fazer engenharia reversa, desmembrar, decompilar ou, de outro modo, tentar criar qualquer código-fonte derivado do programa. O Cartório reconhece que todos os direitos sobre a solução tecnológica pertencem à ParceleCart.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">XII. CONFIDENCIALIDADE E SEGURANÇA</h2>
            <div className="space-y-4">
              <p>12.1. As Partes comprometem-se a manter em sigilo os dados ou especificações a que tiver acesso ou que venha a ter sobre Transações, titular de cartão de crédito ou débito e condições estabelecidas neste Termo.</p>
              <p>12.2. A ParceleCart prestará às autoridades competentes, tais como o Ministério da Fazenda, o Banco Central do Brasil, a Receita Federal, as Secretarias da Fazenda Estaduais e Municipais, Comissões Parlamentares de Inquérito, todas as informações que forem solicitadas em relação ao Cartório ou quaisquer dados relativos às Transações efetuadas nos Cartório.</p>
              <p>12.3. A ParceleCart poderá comunicar ao COAF – Conselho de Controle de Atividades Financeiras, as Transações que possam estar configuradas na Lei 9.613/98 e demais normas relativas à lavagem de dinheiro.</p>
              <p>12.4. O Cartório autoriza e concorda que a ParceleCart, os Credenciadores, Emissores, o Domicílio Bancário e as Bandeiras compartilhem suas informações cadastrais.</p>
              <p>12.5. A ParceleCart se compromete a cumprir e manter-se aderente às regras emanadas pelo PCI (Payment Card Industry) ou qualquer norma posterior que venha a regular a segurança de dados do titular de cartão de crédito ou débito de cartão no mercado de Meios de Pagamento, durante a vigência deste Termo.</p>
              <p>12.6. A obrigatoriedade acima se estende a qualquer fornecedor contratado pelo ParceleCart, cuja atividade seja passível de tráfego, processamento ou armazenamento dos dados do titular de cartão de crédito ou débito do cartão.</p>
              <p>12.7. A ParceleCart deve comunicar imediatamente o Cartório caso tome conhecimento de vazamento dos dados do titular de cartão de crédito ou débito do cartão.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">XIII. PROTEÇÃO DE DADOS PESSOAIS</h2>
            <div className="space-y-4">
              <p>13.1. Para a execução deste Contrato, as partes reconhecem que, em razão do objeto do Contrato Principal, realizam atividades de tratamento de informações relacionadas a pessoas naturais identificadas ou identificáveis (“Dados Pessoais”) e declaram que, no contexto do desempenho de suas obrigações contratuais, cumprirão toda a legislação aplicável a tal tratamento, incluindo, mas não se limitando à Lei nº 13.709/2018, bem como às normas aplicáveis à matéria.</p>
              <p>13.2. As Partes concordam que, no âmbito da execução do Contrato Principal, a Cartório atuará como controladora de dados pessoais e a ParceleCart como operadora, nos termos da legislação aplicável.</p>
              <p>13.3. A ParceleCart reconhece que somente realizará o tratamento de Dados Pessoais a que tenha acesso em razão de suas atribuições sob o Contrato Principal com o objetivo exclusivo de alcançar as finalidades diretamente relacionadas à execução do seu objetivo e ao cumprimento das suas obrigações contratuais.</p>
              <p>13.4. A ParceleCart compromete-se a manter o mais completo sigilo em relação a toda e qualquer informação relacionada às atividades da Cartório, salvo quando tais informações sejam exigidas por requisição de autoridades competentes ou reguladoras, bem como por determinação judicial ou administrativa; sendo certo que a ParceleCart se compromete a cumprir as ordens legais do que lhe for requisitado.</p>
              <p>13.5. A ParceleCart compromete-se a manter a aplicar medidas de segurança da informação técnicas e organizacionais aptas a proteger os Dados Pessoais tratados no âmbito do Contrato Principal. Para tanto, declara e garante que dispõe de processos, controles e políticas de segurança apropriadas e compatíveis com a legislação aplicável, incluindo a adoção de salvaguardas de comunicação para a proteção dos Dados Pessoais contra Incidentes de qualquer natureza.</p>
              <p>13.6. As Partes concordam que caberá, igualmente, a comunicação à outra parte, no prazo de 24 horas, por escrito e de forma detalhada, sobre qualquer Incidente de Segurança da Informação verificado. Para tanto, as partes se comprometem a apresentarem Relatório com todas as informações disponíveis sobre tal Incidente, para que sejam avaliadas e adotadas as medidas cabíveis.</p>
              <p>13.7. Caso alguma pessoa a quem se refere qualquer porção dos Dados Pessoais tratados sob o Contrato Principal (um “Titular”) questione a ParceleCart sobre o tratamento de Dados Pessoais ou solicite o exercício de quaisquer de seus direitos previstos na legislação aplicável, a ParceleCart se compromete a encaminhar tal fato ao Cartório, por escrito, para este adotar as medidas indicadas para o atendimento de tais requisições nos termos da legislação de proteção de dados.</p>
              <p>13.8. A Cartório reconhece a sua responsabilidade, enquanto controladora dos Dados Pessoais, pelo tratamento de Dados Pessoais realizado no âmbito do Contrato Principal</p>
              <p>13.9. Em respeito a legislação aplicável, para a prestação do serviço deste Contrato, a Cartório declara e garante que: (i) esclarece aos titulares de Dados Pessoais como os seus dados podem ser tratados; (ii) está amparada por uma hipótese de tratamento de Dados Pessoais para compartilhar informações com esta ParceleCart; (iii) está ciente de possível transferência internacional de Dados Pessoais para execução dos Serviços avençados.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">XIV. DECLARAÇÕES DO CARTÓRIO</h2>
            <div className="space-y-4">
              <p>14.1. O Cartório declara ter lido e aceita, sem reservas, todas as cláusulas e condições previstas no presente Termo e seus anexos.</p>
              <p>14.2. Neste ato, o Cartório declara que todas as informações prestadas no ato de seu cadastramento são verdadeiras e que está apto a habilitar-se como Cartório nos termos deste Termo.</p>
              <p>14.3. O Cartório declara estar ciente de que o serviço prestado pela ParceleCart não se confunde com os serviços financeiros oferecidos por empresas de Meios de Pagamento, como adquirentes, instituições bancárias ou administradoras de cartão de crédito, constituindo apenas em uma forma de facilitação e acompanhamento da realização de Transações comerciais eletrônicas entre titular de cartão de crédito ou débito e o Cartório.</p>
              <p>14.4. O Cartório declara estar ciente de que é o único responsável e único fiel depositário de todas as suas documentações, declarações e notas fiscais para apresentação e devido recolhimento aos órgãos fiscais competentes, seja no âmbito da união, do estado e município domiciliado, sobre as Transações trafegadas pela plataforma tecnológica ParceleCart.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">XV – DISPOSIÇÕES FINAIS</h2>
            <div className="space-y-4">
              <p>15.1. O Cartório se obriga a utilizar o nome e as marcas da ParceleCart, Credenciadoras e/ou das Bandeiras única e exclusivamente para promover a aceitação dos Meios de Pagamento para os quais foi credenciado, respeitando as características das marcas, os direitos de propriedade intelectual da ParceleCart, Credenciadoras e das Bandeiras.</p>
              <p>15.2. Todos e quaisquer dizeres, anúncios, promoções, marcas, logotipos e demais informações dispostas ou veiculadas pelo Cartório são de única e exclusiva responsabilidade do Cartório, o qual neste ato isenta a ParceleCart de toda e qualquer responsabilidade por conta de tais informações, sua legitimidade e legalidade.</p>
              <p>15.3. Este Termo não estabelece quaisquer vínculos societários, trabalhistas ou previdenciários, tampouco a existência de responsabilidade solidária ou subsidiaria entre a ParceleCart, Credenciadoras, Bandeiras, Emissores e o Cartório.</p>
              <p>15.4. A ParceleCart reserva-se o direito de alterar os termos deste documento a qualquer momento, sem aviso prévio e independentemente de aditivo, bastando, para tanto, postar uma versão revisada em seu website. Qualquer nova versão revisada entrará em vigor assim que postada no website da ParceleCart. A publicação de uma nova versão deverá ser comunicada ao Cartório por e-mail em até 7 dias.</p>
              <p>15.4.1. Se o Cartório não concordar com as alterações comunicadas na forma acima, poderá rescindir este Termo, no prazo de 15 (quinze) dias, contados a partir da data da publicação da alteração. Caso o Cartório não se manifeste em tal prazo, comprovadamente, em contrário a tais alterações, tal fato implicará na sua aceitação plena e irrestrita, sem prejuízo da possibilidade de rescindir o Termo, a qualquer tempo, nos termos deste Termo.</p>
              <p>15.5. A responsabilidade contratual da ParceleCart perante o Cartório, surgida por ocasião da celebração, execução ou rescisão do presente Termo, limitar-se-á aos danos resultantes das ações ou omissões atribuíveis à culpa exclusiva da ParceleCart. A referida responsabilidade limitar-se-á ao pagamento daqueles danos materiais, diretos, quantificáveis, comprováveis e previsíveis quando de sua ocorrência.</p>
              <p>15.6. Todos os termos e condições deste Termo são extensivos e obrigatórios aos sucessores e cessionários autorizados do Cartório e da ParceleCart, que se responsabilizam por seu fiel cumprimento. Se qualquer dos termos, cláusulas ou condições constantes do Termo vier a se tornar ineficaz ou inexequível, a validade e a exequibilidade das demais não será afetada.</p>
              <p>15.7. Qualquer omissão ou tolerância das Partes em relação às obrigações assumidas neste instrumento não será considerada novação contratual ou renúncia, nem prejudicará o direito da parte de exercê-las a qualquer tempo.</p>
              <p>15.8. PROIBIÇÃO DE NEGOCIAÇÃO DOS CRÉDITOS. O Cartório reconhece e concorda, expressamente, que serão vedadas, ineficazes e sem efeito, não produzindo nenhuma consequência relativamente à ParceleCart, a caução, cessão ou transferência, de titularidade, negociações envolvendo quaisquer direitos creditórios que o Cartório detenha junto a ParceleCart, oriundos das Transações, ou o oferecimento em garantia dos créditos decorrentes de Transações, salvo na hipótese de prévia e escrita concordância ou anuência da ParceleCart diretamente com o Cartório.</p>
              <p>15.9. O Cartório concede um direito de uso e de exibir publicamente sua(s) marca(s) comercial(is) durante o prazo deste Termo, com o único propósito de identificar o Cartório cliente da ParceleCart.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">XVI. FORO</h2>
            <p>
              16.1. Este Termo será regido e interpretado de acordo com as leis da República Federativa do Brasil. A comarca da cidade de São Paulo/SP é o foro de eleição deste Termo, sendo facultado à ParceleCart optar pelo foro do domicílio do Cartório.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">ANEXO I – DEFINIÇÕES</h2>
            <div className="space-y-4">
              <p>Para o perfeito entendimento e interpretação deste Termo são adotadas as seguintes definições, grafadas em caixa alta, utilizadas no singular ou no plural:</p>
              <p>(I) “BACEN” – Banco Central do Brasil;</p>
              <p>(II) “Bandeiras” – instituidores de arranjos de pagamento nacionais ou estrangeiros, detentores dos direitos de propriedade e franqueadoras de suas marcas, para uso da ParceleCart e Cartórios, e dos Emissores, mediante a especificação de regras gerais de organização e funcionamento do sistema de Cartões e Meios de Pagamento e/ou produtos;</p>
              <p>(III) “Cartões” – Instrumentos de identificação e de pagamento, físicos ou virtuais, configurados ou apresentados sob a forma de Cartões plásticos, válidos e contendo os sinais distintivos das Bandeiras, capazes de realizar várias funções, disponibilizadas pelos Emissores, para uso pessoal e intransferível dos titulares de cartão de crédito ou débito, aceitos pela ParceleCart;</p>
              <p>(IV) “CHIP” – Microcircuito introduzido no cartão que possibilita o armazenamento de dados confidenciais do titular de cartão de crédito ou débito, sendo a sua leitura realizada por meio equipamento e condicionada ao uso de senha do titular de cartão de crédito ou débito.</p>
              <p>(V) “Contestação de Transação” (“Chargeback”) – Processo que pode resultar na devolução de uma transação, por contestação do titular de cartão de crédito ou débito ou do emissor, de acordo com as regras e prazos definidos pelas Bandeiras;</p>
              <p>(VI) “Credenciadoras” – Empresas responsáveis prestar serviços de credenciamento da ParceleCart e Cartórios no sistema específico de captura, transporte, processamento e/ou repasse de Transações com Cartões, outros Meios de Pagamento e integração com Bandeiras, Emissores, titular de cartão de crédito ou débito e indústria de Cartões.</p>
              <p>(VII) “Domicílio Bancário” – Banco, agência e conta corrente cadastrados pelo Cartório por ocasião do cadastramento e que poderão, nos termos deste Termo, receber créditos decorrentes de Transações.</p>
              <p>(VIII) “Emissores” – empresas nacionais ou estrangeiras, instituições bancárias ou não, autorizadas pelas Bandeiras a emitir e conceder Cartões e/ou disponibilizar produtos, para uso no Brasil e/ou no exterior;</p>
              <p>(IX) “Informações Confidenciais” – informações relacionadas à propriedade intelectual das Partes, as informações de propriedade das Partes que sejam divulgadas à outra Parte nos termos deste Termo, seja em forma impressa ou eletrônica e, as informações contidas neste Termo;</p>
              <p>(X) “Meios de Pagamento” – instrumentos físicos ou eletrônicos com funções de pagamento (múltiplas ou não), aceitos ou que venham a ser aceitos no sistema eletrônico facilitador de pagamentos da ParceleCart, disponibilizadas pelos Emissores, para uso pessoal e intransferível dos titulares de cartão de crédito ou débito;</p>
              <p>(XI) “Titular de Cartão de Crédito ou Débito” – São as pessoas físicas ou jurídicas, possuidoras de cartão e/ou usuárias de Meios de Pagamento, autorizadas a realizar Transações para adquirir os produtos e serviços oferecidos pelo Cartório;</p>
              <p>(XII) “Propriedade Intelectual” – todos os direitos de uso (por licença escrita e em pleno vigor e efeito) de toda propriedade intelectual necessária ou utilizada nas atividades das Partes, bem como todos os softwares necessários para utilizar tais direitos de propriedade intelectual (com contratos de manutenção válidos e exequíveis), sendo as Partes suas legítimas proprietárias, detentoras ou licenciadas;</p>
              <p>(XIII) “Serviços” – Tem o significado disposto na cláusula 2.1 deste Termo; e</p>
              <p>(XIV) “Transações” – Significa a captura, transmissão, processamento de dados e liquidação de operações de pagamento oriundas do uso de Cartões e Meios de Pagamentos por titular de cartão de crédito ou débito.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-bold text-brand-green mb-6">ANEXO II – PROPOSTA</h2>
            <p>
              Integra o presente Termo a Proposta de Parceria Comercial enviada pela ParceleCart previamente ao Cartório por e-mail ou aplicativo de mensagem instantânea, especificando as condições comerciais do acordo ora firmado. Sempre que houver alteração das condições comerciais, a ParceleCart enviará ao cartório as condições atualizadas podendo o Cartório concordar, ou não, com tais condições. Na hipótese do Cartório discordar das novas condições, o presente contrato poderá ser rescindido.
            </p>
          </section>

        </div>
      </div>
    </main>
  );
}
